# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62ba7442161007b5e8ca4ee10fb701fd"
name = "Aurea app"
handle = "aurea-app-prod"
application_url = "https://jacksonville-stuart-poly-desperate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aurea-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://jacksonville-stuart-poly-desperate.trycloudflare.com/auth/callback",
  "https://jacksonville-stuart-poly-desperate.trycloudflare.com/auth/shopify/callback",
  "https://jacksonville-stuart-poly-desperate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://deserve-button-powerpoint-environmental.trycloudflare.com/webhooks"

[pos]
embedded = false
