# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ae600690bcb55f90556027ef3cda65c"
name = "aurea-prod-app"
handle = "aurea-prod-app"
application_url = "https://restriction-jelsoft-futures-authors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aurea-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://restriction-jelsoft-futures-authors.trycloudflare.com/auth/callback",
  "https://restriction-jelsoft-futures-authors.trycloudflare.com/auth/shopify/callback",
  "https://restriction-jelsoft-futures-authors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
